#!/bin/bash

# Up or Down the proxy
SWITCH=$1
# Path that the ss config file in
CONFIG_PATH=/usr/share/aydenlin/shadowsocks/ecs_west.jscon 
# PID of ss-local
SS_LOCAL_PID=0

if [ $SWITCH = "on" ] 
then
    nohup ss-local -c $CONFIG_PATH 2> /dev/null 1> /dev/null &
    echo "ssocks on"
elif [ $SWITCH = "off" ]
then 
    SS_LOCAL_PID=$(ps -ax | grep "\bss-local -c" | awk '{print $1}')
    kill 9 $SS_LOCAL_PID 2> /dev/null
    echo "ssocks off"
else
    echo "usage: ssocks on or ssocks off"
fi
